### ISSUE TITLE
error decoding login

### ISSUE THREAD

**Issue by saxtorinc** [dimaskiddo/go-whatsapp-cli#3] opened 2020-03-27 07:43 UTC
go-whatsapp-cli $  error decoding login%!(EXTRA *json.UnmarshalTypeError=json: cannot unmarshal array into Go value of type map[string]interface {})

**Comment by dimaskiddo** [comment] 2020-03-28 14:24
Try to pull and update the code, should be fixed
The error is caused by whatsapp blocking to get their server version, now it should be set manualy

By default now it's set to version 0.4.1300

**Closed as completed by dimaskiddo** 2020-03-28 14:24 UTC
